version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo === INSTALL YOUR PACKAGES HERE!!! === 
      - pip3 install cfn-lint
    
  pre_build:
    commands:
      - echo === CHECKING IF PYTHON WAS INSTALLED ===
      - python3 --version
      - echo === CHECKING FOR AMAZON VERSION ===
      - aws --version
      - echo === CHECKING FOR CFN-LINT ===
      - cfn-lint --version
    
  build:
    commands:
      - echo === BUILD TEMPLATE HERE ===
      - cfn-lint ec2-user-data-template-B.yml
      - echo ***TEMPLATE VALIDATED***
      - aws cloudformation validate-template --template-body file://ec2-user-data-template-B.yml
      - echo === BUILD TEMPLATE HERE ===
      - aws cloudformation package --template-file ec2-user-data-template-B.yml --s3-bucket my-deployed-artifact --output-template-file build-artifact-template.yaml
      
    
  post_build:
    commands:
      - echo === WHAT TO DO WHEN BUILD IS COMPLETE ===
      - echo Build completed at `date` # Prints out the current time in
    
artifacts:
  files:
    - build-artifact-template.yaml # Creates the zip file (artifact) ---> in the deploy stage
   